version: "3.8"

services:
  restaurant-service:
    extends:
      file: restaurant-manager-go/docker-compose.yaml
      service: restaurant-service
    networks:
      - app-network

  restaurant-next:
    extends:
      file: restaurant-manager-next/docker-compose.yaml
      service: restaurant-next
    networks:
      - app-network

  db:
    extends:
      file: infra/db/docker-compose.yaml
      service: db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    extends:
      file: infra/sso/docker-compose.yaml
      service: keycloak
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  app-network:
    external: true

volumes:
  postgres_data:
    external: true
  keycloak_data:
    external: true

