version: "3.8"

services:
  restaurant-next:
    user: root
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    external: true

