version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  app-network:
    external: true

volumes:
  keycloak_data:
